---
abstract: "Run code at the end of the compiling scope's runtime."
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hook-AfterRuntime
provides:
  Hook::AfterRuntime:
    file: lib/Hook/AfterRuntime.pm
    version: 0.004
requires:
  B::Hooks::Parser: 0.09
  Exporter: 5.57
resources:
  bugtracker: http://github.com/exodist/Hook-AfterRuntime/issues
  homepage: http://open-exodus.net/projects/Hook-AfterRuntime
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Hook-AfterRuntime
version: 0.004
